version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html
      - ../_docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
        context: ./
        dockerfile: Dockerfile
    image: php
    container_name: "php"
    working_dir: /var/www/html
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
      - ./logs:/tmp/xdebug_log
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=server
    networks:
      - app-network
  mysql:
    image: mysql:5.6.51
    container_name: "mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bloomex
      MYSQL_USER: bloomex
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - app-network
volumes:
  mysql:
networks:
  app-network:
    name: 'network'
    driver: bridge
